#ifndef _PY32YYXX_LL_H_
#define _PY32YYXX_LL_H_
/* LL raised several warnings, ignore them */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#ifdef __cplusplus
  #pragma GCC diagnostic ignored "-Wregister"
#endif

/* Include Low Layers drivers */
#include "py32yyxx_ll_adc.h"
#include "py32yyxx_ll_bdma.h"
#include "py32yyxx_ll_bus.h"
#include "py32yyxx_ll_comp.h"
#include "py32yyxx_ll_cordic.h"
#include "py32yyxx_ll_cortex.h"
#include "py32yyxx_ll_crc.h"
#include "py32yyxx_ll_crs.h"
#include "py32yyxx_ll_dac.h"
#include "py32yyxx_ll_dcache.h"
#include "py32yyxx_ll_delayblock.h"
#include "py32yyxx_ll_dlyb.h"
#include "py32yyxx_ll_dma.h"
#include "py32yyxx_ll_dma2d.h"
#include "py32yyxx_ll_dmamux.h"
#include "py32yyxx_ll_exti.h"
#include "py32yyxx_ll_fmac.h"
#include "py32yyxx_ll_fmc.h"
#include "py32yyxx_ll_fmpi2c.h"
#include "py32yyxx_ll_fsmc.h"
#include "py32yyxx_ll_gpio.h"
#include "py32yyxx_ll_hrtim.h"
#include "py32yyxx_ll_hsem.h"
#include "py32yyxx_ll_i2c.h"
#include "py32yyxx_ll_icache.h"
#include "py32yyxx_ll_ipcc.h"
#include "py32yyxx_ll_iwdg.h"
#include "py32yyxx_ll_lpgpio.h"
#include "py32yyxx_ll_lptim.h"
#include "py32yyxx_ll_lpuart.h"
#include "py32yyxx_ll_mdma.h"
#include "py32yyxx_ll_opamp.h"
#include "py32yyxx_ll_pka.h"
#include "py32yyxx_ll_pwr.h"
#include "py32yyxx_ll_rcc.h"
#include "py32yyxx_ll_rng.h"
#include "py32yyxx_ll_rtc.h"
#include "py32yyxx_ll_sdmmc.h"
#include "py32yyxx_ll_spi.h"
#include "py32yyxx_ll_swpmi.h"
#include "py32yyxx_ll_system.h"
#include "py32yyxx_ll_tim.h"
#include "py32yyxx_ll_ucpd.h"
#include "py32yyxx_ll_usart.h"
#include "py32yyxx_ll_usb.h"
#include "py32yyxx_ll_utils.h"
#include "py32yyxx_ll_wwdg.h"
#pragma GCC diagnostic pop
#endif /* _PY32YYXX_LL_H_ */
