name: release

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          path: source
          submodules: recursive

      - name: Build clean release package
        run: |
          mkdir Arduino-PY32
          rsync -a \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='.gitignore' \
            --exclude='.gitmodules' \
            source/ Arduino-PY32/
          find Arduino-PY32 -name .git -prune -exec rm -rf {} +
          archive_name="Arduino-PY32-${GITHUB_REF_NAME//\//-}.zip"
          zip -r "$archive_name" Arduino-PY32

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.zip"
          allowUpdates: true

      - name: Send repository_dispatch event to package json
        run: |
          curl -X POST https://api.github.com/repos/PY32Duino/Arduino-pack-json-ci/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.USER_TOKEN }} \
          --data '{"event_type": "release"}'
